### ISSUE TITLE
BBN/Tone with multiple durations - desired data not displayed

### ISSUE THREAD

**Issue by nohelix** [Auerbach-Lab/Behavior-autoanalysis#74] opened 2023-08-09 21:31 UTC
Issue:
100 ms files now that we are increasing duration following hearing loss are not showing up because everything is limited to min_duration.

Attempts to change to min_duration to today's min cause breaking on rats in training.

**Comment by nohelix** [comment] 2023-08-10 01:19
Sorry for the bad/unclear bug report.

Issue:
Post hearing loss, we start at 50ms and increase up to 100 then 300ms durations for testing temporal integration. The code as written strictly limits the listed summary days to the **minimum** time duration ever seen for files in with the same task and detail. This means that if we increase the time window, those files are filtered out of being included in the trials included in the supervisor summary.

Expected behavior:
The day's actual run is in the displayed/included runs in the supervisor table for a rat. Ideally the table, in the case of BBN or tone files, would be restricted to **only** files with the **same** time window. For single window files (i.e. only one duration for all stimuli in a complete block) we want to limit the summary table (r in the code) to files matching the **current** duration.
Expected cause of the behavior (i.e. watch out for introducing issues when patching): On 'mixed' files that have a variable window of 50-300ms within a block, we only want to display the smallest window.

Steps to reproduce:
[run_archive.zip](https://github.com/Auerbach-Lab/Behavior-autoanalysis/files/12307916/run_archive.zip)
Using admin tools > _supervisor-summarize-custom.R_ select the Blue rats to summarize `set filter(str_detect(Rat_name, "Blue"))`
Once the xlsx file builds and opens, the most recent run data included will be on 20230807 with a file name of BBN_20-80dB_50ms_4s. No data for 20230808 or 20230809 will be shown both of which are in the run_archive with file names of BBN_20-80dB_100ms_4s (task = Training, detail = Alone).
You can verify these runs are in the database:
`run_archive %>% filter(rat_name %in% c("Blue1")) %>% 
  unnest_wider(assignment) %>%
  unnest_wider(stats) %>%
  mutate(hit_percent = hit_percent * 100, FA_percent = FA_percent * 100) %>%
  select(date, rat_name, weight, trial_count, hit_percent, FA_percent, file_name, experiment, phase, task, detail) %>%
  arrange(desc(date))`

**Comment by tofof** [comment] 2023-08-11 17:22
Zip inadequate for reproduction; no blue rats appear at all while running supervisor summarize, and only 12 rats are listed overall. I assume this is either a rat_archive issue or an issue with missing the needed entries in the correct experiment's Rdata archive.

**Comment by nohelix** [comment] 2023-08-11 17:56
[rat_archive.zip](https://github.com/Auerbach-Lab/Behavior-autoanalysis/files/12323989/rat_archive.zip)
Will also be necessary to reproduce. This should be sufficient with the validation commented out (line 1043)

**Comment by tofof** [comment] 2023-08-11 20:50
> Expected cause of the behavior (i.e. watch out for introducing issues when patching): On 'mixed' files that have a variable window of 50-300ms within a block, we only want to display the smallest window.

Do you have an example of such a file to verify I don't break this behavior? I can prune run_archive of runs since that file for that rat easily enough, so that it gets used as the 'today' run for that rat.

**Comment by nohelix** [comment] 2023-08-16 14:53
> By 'mixed' you mean BBN/Tones with detail Mixed, right?

Yes, I meant BBN files which have the detail Mixed. Note that tone mixed is different as that is multiple frequencies not durations. They should have names like "BBN_20-80dB_50-300ms_8s" where the 50-300ms encodes that there are multiple stimuli durations. They will be `analysis_type` "BBN Mixed Duration". The files have a block size of 30 instead of 10.

>  Do you have an example of such a run (rat & date) to verify I don't break this behavior?

For examples in `run_archive` see Green11 on:
- Mixed Duration   12/10/2022  `run_archive %>% filter(rat_name %in% c("Green11") & date == 20221210)`
- Single Duration   12/16/2022  `run_archive %>% filter(rat_name %in% c("Green11") & date == 20221216)`

> What precisely do you mean by time window? That's not a term that appears anywhere that I know of. Only one number is ever in the Dur (ms) column by the point that the entries to include are being pruned. 

By time window I was referring to duration. I believe duration in the sup-sum is derived from the summary column of the `run_archive`. In `run_archive`, the summary column contains a tibble with the `duration` column (`run_archive %>% filter(rat_name %in% c("Green11") & date == 20221216) %>% .$summary %>% .[[1]] %>% .$duration`), which can have a single value (300) in the case of _Single Duration_ files (see Green 11, 12/16/2022) or for _Mixed Duration_ files, such as Green11 on 12/10/2022, it has 3 values (50, 100, 300).

Rephrase:
~~For single window files (i.e. only one duration for all stimuli across all blocks) we want to limit the summary table (r) to files matching the current duration.
Ideally the table, in the case of BBN or tone files, would be restricted to only files with the same time window.~~
Ideally, I would like the displayed rat run history to be limited to only files that include the day's current duration. In the case of _Mixed Duration_ files, that means that the single displayed duration matches the day's current duration. So if the day's run is "BBN_20-80dB_100ms_8s" which has a duration of 100ms, then the displayed rxn time for files such as "BBN_20-80dB_50-300ms_8s" would be for 100ms, not 50 or 300ms.

**Comment by nohelix** [comment] 2023-08-17 01:06
Currently Reaction Time (Rxn) is stored by Duration (`Dur (ms)`), Frequency (`Freq (kHz)`) and intensity (`Inten (dB)`). In this case, the Frequency is the same for all the trials so irrelevant.  For non-thresholding days (i.e. detail not "TH"), we want a reaction time for 60dB. (see the code on line s 586 to 601 for where this is done). The desired intensity for threshold files is found on line 570 since we don't have a consistent shared intensity across all files (`slice(which.min(`Inten (dB)`))` which I believe returns the most common minimum intensity).

Location in `run_archive`:
`run_archive %>% filter(rat_name %in% c("Green11") & date == 20221210) %>% unnest_wider(stats) %>% .$reaction`

**Comment by nohelix** [comment] 2023-08-17 02:15
https://github.com/Auerbach-Lab/Behavior-autoanalysis/blob/476cba765e9eca730b8013542628f29e6d0665fa/supervisor-summarize.R#L522C41-L522C41

**Comment by tofof** [comment] 2023-08-17 21:41
Is BBN-TH-Mixed a valid combination? There is no way for me to deduce this from the experiment csv.

If so, it's more complicated - altering line 576 means you no longer have the 'use the minimum' behaivor for those files.

**Comment by tofof** [comment] 2023-08-17 23:04
Closed by [bb191af](https://github.com/Auerbach-Lab/Behavior-autoanalysis/commit/bb191af665db58308c23eebedb1cf43a1e7b8717)

**Comment by tofof** [comment] 2023-08-17 23:04
Closed by [bb191af](https://github.com/Auerbach-Lab/Behavior-autoanalysis/commit/bb191af665db58308c23eebedb1cf43a1e7b8717)

**Closed by tofof** 2023-08-17 23:04 UTC
Labels: bug, priority: high, at: supervisor
